spring:
  jpa: 
    properties:
     javax:
      persistance:
        validation:
          mode: none
  profiles:
    active:
       - dev
hoaxify:
  upload-path: picture-storage
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:./devdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
hoaxify:
  upload-path: storage-dev#  data:#    web:#      pageable:#        page-parameter: currentPage
#        size-parameter: pageSize
  