spring:
  jpa: 
    properties:
     javax:
      persistance:
        validation:
          mode: none
  profiles:
    active:
       - dev
hoaxify:
  upload-path: picture-storage
---
spring:
  profiles: dev
hoaxify:
  upload-path: storage-dev#  data:#    web:#      pageable:#        page-parameter: currentPage
#        size-parameter: pageSize
  