#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update
spring:
  jpa: 
    properties:
     javax:
      persistance:
        validation:
          mode: none#  data:#    web:#      pageable:#        page-parameter: currentPage
#        size-parameter: pageSize
  